# Get 6 of coffee store in Sydney
###
GET https://api.foursquare.com/v3/places/nearby?query=coffee&limit=6 HTTP/1.1
Accept: application/json
Authorization: {{foursquareAuthorizationHeader}}
###

#POST createCoffeeStore
POST http://localhost:3000/api/createCoffeeStore HTTP/1.1
content-type: application/json

{
    "id": "6",
    "name": "",
    "address": "address 1",
    "voting": 1,
    "neighbourhood": "neighbour 1",
    "imgUrl": "imgUrl 1"
}
###
# GET getCoffeeStoreById
GET http://localhost:3000/api/getCoffeeStoreById?id=4b0c5685f964a520703b23e3 HTTP/1.1
###

# PATCH favouriteCoffeeStoreById
PATCH  http://localhost:3000/api/favouriteCoffeeStoreById HTTP/1.1
Content-Type: application/json

{
    "id": "4b0c5685f964a520703b23e3"
}
###