import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
// import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  let coffeeStoresData;
  const options = {
    method: "GET",
    headers: {
      Accept: "application/json",
      Authorization: "fsq31U8dW5aJ1LnbxCU411jf5D/IHXInpdLefCdJTqVn3Ss=",
    },
  };

  try {
    const response = await await fetch(
      "https://api.foursquare.com/v3/places/search?query=coffee&near=sydney&limit=6",
      options
    );

    const data = await response.json();
    coffeeStoresData = data.results;
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("banner button clicked");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Detector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="Show me" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero-image"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Sydney Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.fsq_id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl || "/static/hero-image.png"}
                  href={`/coffee-store/${coffeeStore.id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
